# Generated by Django 3.0.3 on 2021-08-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellerdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_id', models.IntegerField()),
                ('seller_address', models.CharField(max_length=50)),
                ('seller_phoneno', models.IntegerField()),
            ],
        ),
    ]
