# Generated by Django 3.0.3 on 2021-08-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sellerdata',
            new_name='sellersdata',
        ),
    ]
