# Generated by Django 3.0.3 on 2021-08-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_auto_20210817_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersdata',
            name='seller_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sellersdata',
            name='seller_phoneno',
            field=models.BigIntegerField(),
        ),
    ]
