# Generated by Django 3.0.3 on 2021-08-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_auto_20210817_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersdata',
            name='seller_phoneno',
            field=models.BigIntegerField(default=0),
        ),
    ]
