# Generated by Django 3.0.3 on 2021-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donorapp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('last_donate_date', models.DateField()),
            ],
        ),
    ]
