# Generated by Django 3.0.3 on 2021-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_code', models.IntegerField()),
                ('product_description', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
