# Generated by Django 3.0.3 on 2021-08-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegitableapp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegitableid', models.IntegerField()),
                ('vegitablename', models.CharField(max_length=20)),
                ('vegitabledescription', models.CharField(max_length=100)),
                ('vegitableprice', models.IntegerField()),
            ],
        ),
    ]
